# Generated by Django 4.2.3 on 2023-08-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='chat_id',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
