# Generated by Django 4.2.3 on 2023-07-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.IntegerField(verbose_name='habit duration'),
        ),
    ]
