# Generated by Django 4.2.3 on 2023-07-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'habit', 'verbose_name_plural': 'habits'},
        ),
    ]
